---
env:
  global:
    - atf_version="2.3"
    - uboot_version="2020.04"
    - TRAVIS_TAG=uboot-${uboot_version}-atf-${atf_version}

arch:
  - arm64

language: c
os: linux
dist: bionic

addons:
  apt:
    packages:
      - bc
      - device-tree-compiler
      - swig
script:
  - platform_name="lepotato" ./build
  - platform_name="renegade" ./build
  - platform_name="tritium" ./build
deploy:
  provider: releases
  api_key:
    secure: ioKF3/+AC4luCu/TgI9WpCr395xE1kQQpdPXv2o37X5efyEF0oRgeQFPMN7IverD4GamwjKFamribv6a47yIs1+GWzpn2pPgYoskt5zK432NSIrWt83VOBwAFhm4VHtnSyjjxqvM22/LD1AJjmdX+Vwys3aJ6dvtkLzqcfz050DrIhkSBkWW+AB4J8nLm6eqm6bQ82ctq+Sl5KMk5VRMq14rzvdAUqylBna6uq3UrwTdFslB1gbw43k1u3J/a1RUPCuP8okng7OPhgqCD/2EeVsw6L7Fc65HoqWJ8oSAnGcYGH2EU07J5p2ziJ7r61Kkd6mGIZYwSkw/R0+P62993FjbFLU9oFub4UekVqdN4hNZhzs42mtV9YuLfS99ru5U+x8dI0yVYSh68bR0/Po7nH6qyyVUPXVBJdokHr8diUI6/mVDL62NXOxFd2Qnaxe0GskqP86RA2ruGEZSXoS2PdGgEV7s08sePir/NPXYYP+hA/7+MwS19EC/i4h7kr0zuwXyXD2vc6b4px3XkNl7if9GZ9/rq5Jj2ScF5dB+PQchyIMLCUhLwq12IiS2TxDrB3AExoEO13m5njSSrsUG5Tskv2ea1JSXoKaKAwg8pFAda15ap/aVVrBeRuZTuoCDwjOznSp4Uqc2aGWCRPzPSJkZIZe1wgD7IvRMPyjIxss=
  file: release/*.tar.xz
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
    repo: damex/u-boot
