#!/usr/bin/env bash

: "${uboot_version:=2020.04}"
: "${atf_version:=2.3}"

[[ -z "${platform_name}" ]] && echo "Please define a platform_name." && exit 1

if [[ -f "platforms/${platform_name}" ]] ; then
  source "platforms/${platform_name}"
  if [[ -z "${uboot_config}" ]] ; then
    echo "Platform configuration is incomplete."
    exit 1
  fi
else
  echo "Platform configuration does no exist."
  exit 1
fi

prepare_atf() {
  if [[ ! -f "atf-${atf_version}.tar.gz" ]] ; then
    curl -L https://github.com/ARM-software/arm-trusted-firmware/archive/v${atf_version}.tar.gz -o atf-${atf_version}.tar.gz
    tar xpf atf-${atf_version}.tar.gz
  fi
}

prepare_uboot() {
  if [[ ! -f "u-boot-${uboot_version}.tar.gz" ]] ; then
    curl -L https://github.com/u-boot/u-boot/archive/v${uboot_version}.tar.gz -o u-boot-${uboot_version}.tar.gz
    tar xpf u-boot-${uboot_version}.tar.gz
  fi
}

build_atf() {
  if [[ -n "${atf_platform}" ]] ; then
    pushd "arm-trusted-firmware-${atf_version}"
    make distclean
    make PLAT="${atf_platform}" bl31
    popd
  fi
}

build_uboot() {
  pushd "u-boot-${uboot_version}"
  make distclean
  make "${uboot_config}"
  if [[ -n "${atf_build_binary}" ]] ; then
    BL31="../arm-trusted-firmware-${atf_version}/${atf_build_binary}" make
  else
    make
  fi
  popd
}

prepare_release() {
  mkdir -p "release"
  pushd "release"
  if [[ -n "${atf_platform}" ]] ; then
    release_directory="${platform_name}-uboot-${uboot_version}-atf-${atf_version}"
  else
    release_directory="${platform_name}-uboot-${uboot_version}"
  fi
  release_archive="${release_directory}.tar.xz"
  mkdir "${release_directory}"
  for uboot_build_binary in "${uboot_build_binaries[@]}" ; do
    cp "../u-boot-${uboot_version}/${uboot_build_binary}" "${release_directory}"
  done
  tar -cJf "${release_archive}" "${release_directory}"
  popd
}

if [[ -n "${1}" ]] ; then
  "${1}"
else
  prepare_atf
  build_atf
  prepare_uboot
  build_uboot
  prepare_release
fi
